name: Dispatch-CICD-pre-release

on: workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      LAFTOOLS_ROOT: /home/runner/work/LafTools/LafTools-M-pre
      TAG_MODE: false
      DOCKER_PKG_BUILD_MODE: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.21

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Run LafTools Copy
        id: runlaftoolscopy
        run: |
          cp -a /home/runner/work/LafTools/LafTools /home/runner/work/LafTools/LafTools-M-pre
          chmod +x /home/runner/work/LafTools/LafTools-M-pre/pipeline/tools/get-web2-version.sh
          export crtVersion=`$LAFTOOLS_ROOT/pipeline/tools/get-web2-version.sh`

      - name: Run build script
        id: runbuildscript
        run: |
          npm i -g typescript
          cd ./modules/web2
          cd ../../
          cd ./pipeline
          chmod +x ./build-all.sh
          ./build-all.sh "${{steps.get_version.outputs.VERSION}}"

      - name: US Pkg Release 1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.US_APP_SSH_HOST }}
          port: ${{ secrets.US_APP_SSH_PORT }}
          username: ${{ secrets.US_APP_SSH_USERNAME }}
          key: ${{ secrets.US_APP_SSH_KEY }}
          script: |
            echo 'Running some command'
            ls -la 
            mkdir -p /home/appuser/PkgRelease-dist

      - name: US Pkg Release 2
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.US_APP_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: US Pkg Release 3
        run: |
          set -e
          crtVersion=`/home/runner/work/LafTools/LafTools-M-pre/pipeline/tools/get-web2-version.sh`
          sftp -o StrictHostKeyChecking=no -P ${{ secrets.US_APP_SSH_PORT }} ${{ secrets.US_APP_SSH_USERNAME }}@${{ secrets.US_APP_SSH_HOST }} <<EOF
            mkdir /home/appuser/PkgRelease-dist/${crtVersion}
            put /home/runner/work/LafTools/LafTools-M-pre/dist/pkg/* /home/appuser/PkgRelease-dist/${crtVersion}/
          exit
          EOF
          if [ $? -ne 0 ]; then
            echo "Failed to upload files to US"
            exit 1
          fi
          rm ~/.ssh/id_rsa -rf
