name: Test Web2 and Server2

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
    env:
      LAFTOOLS_ROOT: /home/runner/work/LafTools/LafTools

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm and dependencies for web2
        run: |
          cd $LAFTOOLS_ROOT/modules/web2
          npm i -g pnpm
          npm i -S -D --force

      - name: run vite test for web2
        run: |
          cd $LAFTOOLS_ROOT/modules/web2
          npx vitest run

      - name: Install Deps for bootstrap
        run: |
          cd $LAFTOOLS_ROOT/modules/bootstrap
          npm i -g pnpm
          npm i -S -D --force
          npm run build

      - name: run vite test for bootstrap
        run: |
          cd $LAFTOOLS_ROOT/modules/bootstrap
          chmod +x ./pipeline/build-tsc.sh
          ./pipeline/build-tsc.sh
          npx vitest run

      - name: server2 install
        run: |
          cd $LAFTOOLS_ROOT/modules/server2
          npm i -g pnpm
          npm i -S -D --force

      - name: server2 build
        run: |
          cd $LAFTOOLS_ROOT/modules/server2
          npm run build
          npm run test
